spring:
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:5432/WatchRecommendation
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
